# Generated by Django 2.1.2 on 2018-11-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0007_auto_20181029_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Album',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
        migrations.AddField(
            model_name='user',
            name='passWord',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
