# Generated by Django 2.1.2 on 2018-12-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0009_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='DefaultBehavior',
            field=models.CharField(choices=[('RandomSong', 'RandomSong'), ('DefaultSong', 'DefaultSong'), ('Voice', 'Voice'), ('Beep', 'Beep')], default='DefaultSong', max_length=50),
        ),
    ]
