# Generated by Django 2.1.2 on 2018-12-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0011_systemsettings_defaultsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='DefaultBehavior',
            field=models.CharField(choices=[('RandomSong', 'RandomSong'), ('DefaultSong', 'DefaultSong'), ('Voice', 'Voice')], default='DefaultSong', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='FavouriteSong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestHandler.Song'),
        ),
    ]
