# Generated by Django 2.1.4 on 2018-12-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0013_auto_20181215_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FavouriteSong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requestHandler.Song'),
        ),
    ]
