# Generated by Django 2.1.2 on 2018-10-18 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongName', models.CharField(max_length=100)),
                ('Album', models.CharField(max_length=100)),
                ('FilePath', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('FavouriteSong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestHandler.Song')),
            ],
        ),
    ]
