# Generated by Django 2.1.2 on 2018-10-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0002_auto_20181028_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
    ]
