# Generated by Django 2.1.2 on 2018-10-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0003_auto_20181028_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='usersImages/'),
        ),
    ]
