# Generated by Django 2.1.2 on 2018-10-29 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0005_auto_20181028_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FavouriteSong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestHandler.Song'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.ImageField(null=True, upload_to='usersImages/'),
        ),
    ]
