# Generated by Django 2.1.2 on 2018-10-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0006_auto_20181029_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Album',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
